openedx/frontend-app-account

package-lock.json, package.json, src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/actions.js, src/account-settings/components/PasswordReset.jsx, src/account-settings/components/ThirdPartyAuth.jsx, src/account-settings/sagas.js, src/account-settings/service.js
- Change order of fields, update edx-bootstrap to latest.
- Password reset now sends email along with post request.
- Clicks on "reset password" now a noop while in progress.
- add best guesses for help text
=> fix: verify parity

src/account-settings/service.js
Makes it possible to delete a social link.
=> fix: send social link value when empty string is supplied

src/site-language/service.js
Adding the `X-Requested-With: XMLHttpRequest` header to the post request shows Django that this is an AJAX request so it will no longer redirect our request (it was getting bounced to edx.org and redirected again to edx.org/dashboard taking seconds to load).
Related Axios Thread: https://github.com/axios/axios/issues/1322
Django Reference: https://docs.djangoproject.com/en/2.2/topics/i18n/translation/#the-set-language-redirect-view
=> fix: add xhr header to eliminate redirects on setlang

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/actions.js, src/account-settings/components/DeleteMyAccount.jsx, src/account-settings/components/JumpNav.jsx, src/account-settings/reducers.js, src/account-settings/sagas.js, src/account-settings/service.js, src/components/App.messages.jsx, src/environment.js
Still needs:
- Add "you must enter a password" error state on confirmation modal if the password field loses focus while it's blank-- I propose doing this as a fast follow.
Note: Seeing console error: "Each child in a list should have a unique "key" prop."  (@abutterworth this looks like a Paragon thing with Modal's Buttons)
=> feat: delete my account

src/account-settings/AccountSettingsPage.jsx, src/account-settings/components/DeleteMyAccount.jsx, src/account-settings/selectors.js
Also change the misleading variable name hasLinkedSocial.  The knowledge base refers to TPAs as "linking to a social media account" (sigh) but they're referred to as TPA providers in the rest of this repo.
=> fix(delete my account): correctly expose Third Party Auth providers

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/components/EditableField.jsx, src/account-settings/components/EmailField.jsx, src/account-settings/constants/index.js, src/account-settings/selectors.js, src/account-settings/service.js
Add a clickable placeholder for empty fields. For empty static fields, show a message indicating no value is set.
All select fields have placeholder options that can be selected to delete the value.
=> Add empty states and ability to delete values from select fields

src/account-settings/ThirdPartyAuth.jsx, src/account-settings/actions.js, src/account-settings/reducers.js, src/account-settings/sagas.js
pending and complete states for disconnecting third party auth accounts are now specific to each provider rather than shared. This prevents the spinner from showing up on multiple third party accounts when unlinking one.
=> fix: per provider disconnection states for third party auth

src/account-settings/reducers.js, src/account-settings/third-party-auth/data/reducers.js
Two problems:
- The auth providers were being added to the wrong part of the store.
- The ThirdPartyAuth component expected them to have the name “providers”, not “authProviders” - great reason to keep names consistent!
=> Fix third party auth naming issues

src/account-settings/data/sagas.js
We were calling the setlang and preferences endpoints in parallel - it’s not clear whether this might create a race condition.  Instead, we now call preferences first, followed by i18n/setlang.  This matches the behavior of the django-based account settings page.
=> Small refactor to make updating the site language sequential

src/account-settings/AccountSettingsPage.jsx
This patch would fix timezone dropdown which
doesn't change  value on selection.
PROD-1349
=> Fix timezone dropdown under Site Preferences

src/account-settings/data/service.js
Profile manager banner should only be visible if:
- a learner is linked to an enterprise
- that enterprise manages the settings
Also, it should display the name of the active enterprise in case if a learner is linked to multiple enterprises. 
**Jira**: https://openedx.atlassian.net/browse/ENT-2741
=> ENT-2741: Fixed Profile Manager Banner Scenario

src/account-settings/coaching/data/service.js
A user without coaching data should no longer see the toggle
=> Default eligble for coaching to false

src/account-settings/data/service.js
This PR fixes the bug reported by @staubina, i.e., when a learned is not linked to any enterprises and no enterprise is returned, it returns `TypeError: Cannot read property 'enterprise_customer' of undefined.
=> Handled no enterprise returned case

src/account-settings/coaching/CoachingConsent.jsx, src/account-settings/coaching/data/service.js
Before this fix, we were having an issues where upon the first time a
user signs up with the coaching form, the phone number would not save.
This was because of the way we patch the user in the form. The phone
number was saving properly, then getting overwritten with `null`.
This fixes that issue, and also cleans up an error message.
=> MICROBA-hotfix: coaching sign-up save phone number

src/account-settings/coaching/CoachingConsent.jsx, src/account-settings/coaching/data/service.js
Prior to this, if you attempted to sign up for coaching and failed, then went to decline, you would be sent to the success screen instead of redirected. This also removes the default from the coaching API check now that it won't 404 when the user requests their own data.
=> Reset coaching submission state on submit

src/account-settings/coaching/CoachingConsent.jsx, src/account-settings/data/actions.js, src/account-settings/data/reducers.js, src/account-settings/data/sagas.js
Originally, we had it set up so that the coaching consent form saved 33
values in parallel. This add a new saga (saveMultipleSettings) to save
those 3 values in sync. This way, if one fails, the rest of the calls
fail.
Something to watch out for here: the order matters. The array that you
give the save function must be ordered in the way you need the data
saved.
=> Prevent phone_number save on coaching save failure

src/account-settings/data/reducers.js, src/account-settings/data/utils/reduxUtils.js, src/account-settings/data/utils/reduxUtils.test.js, src/account-settings/reset-password/RequestInProgressAlert.jsx, src/account-settings/reset-password/ResetPassword.jsx, src/account-settings/reset-password/data/actions.js, src/account-settings/reset-password/data/reducers.js, src/account-settings/reset-password/data/sagas.js
Recently we have changed rate limiting configuration for password reset endpoint to one request per email and IP. I have added the frontend functionality to show proper error message to users.
PROD-1427
=> Handle 403 password reset response.

.env.development, src/account-settings/coaching/CoachingConsent.jsx, src/account-settings/coaching/CoachingToggle.jsx, src/account-settings/data/reducers.js, src/account-settings/data/sagas.js, src/account-settings/data/service.js
This fixes a few little bugs in the system as well as the one listed in
the ticket.
* We no longer make an extra API call to user profile when toggling
coaching
* The user now must toggle coaching off to save a non-eligible phone
number
* If the user changes to another US based phone number, or is not
consented to coaching, the phone number will save as normal.
* SAVE_MULTIPLE_SETTINGS now leverages the SAVE_SETTINGS action for a full redux log and a synchronous execution.
* coaching toggled on by default in dev
=> MB-366 don't save non eligible coaching number

src/account-settings/coaching/CoachingConsent.jsx, src/account-settings/coaching/CoachingConsentForm.jsx, src/account-settings/coaching/test/CoachingConsent.test.jsx, src/account-settings/coaching/test/__snapshots__/CoachingConsent.test.jsx.snap
We were having issues with how the coaching consent form was sending
data. Previously, we were hitting 2 endpoints - one from the coaching
plugin, and one from the LMS. This changes fixes a few issues:
* CoachingConsent now hits one api that handles saving the phone_number,
full_name, and coaching_consent.
* This component does not need to share any of this data, so it is not
connected to Redux. Everything to do with patching is done in the
CoachingConsent component.
* Fetching data is still done through actions provided by redux.
* This change does not effect the fields in the root account settings
page
* Also fixes an issue where the 404 error message was showing up at the
bottom of every page.
=> MB-17: Refactor coaching_consent form

src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationPage.jsx, src/id-verification/data/service.js, src/id-verification/panels/SubmittedPanel.jsx, src/id-verification/panels/SummaryPanel.jsx
[MST-282: IDV Redirect Back to Course When Starting IDV from Course Page](https://openedx.atlassian.net/browse/MST-282)
Takes in course run key as a query string and stores it in session storage, redirecting the user to the course at the end of the flow. If no key is given, the user will be redirected back to the dashboard as normal.
=> Persist courseRunKey in ID verification flow

src/id-verification/IdVerification.messages.js, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx
[MST-326](https://openedx.atlassian.net/browse/MST-326)
Temporary removal of image upload component from IDV flow. This component may be reimplemented at a later date with modifications.
- Camera access is required to successfully complete the process.
- If the user blocks camera access or camera access is otherwise unavailable, they will receive an error message and a button to return to the dashboard or course, depending on where they entered the IDV flow from.
----
=> ID Verification: Hide image upload component

src/account-settings/coaching/CoachingToggle.jsx
This change passes the ID of the form we want to close to the `saveMultipleSettings` action, allowing it to close when the call comes back successfully. ([See these lines in the the saga.](https://github.com/edx/frontend-app-account/blob/0196245c13b820f2a8643efab08c4fd172196486/src/account-settings/data/sagas.js#L122-L125))
Previously, the phone number field would not close while coaching was toggled on:
https://www.loom.com/share/31557612cecb4acfa63d9bfa30979095
Now it does:
https://www.loom.com/share/cc2f4b8e7b25404ca2628f7b7baaae00
MICROBA-463
=> MICROBA-463 Collapse phone number field when coaching toggled on

src/account-settings/demographics/DemographicsSection.jsx, src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
This PR makes the `Why does edX collect this information?` link follow the same styling as helper text in other sections. (The "`Optionally, link your personal accounts to the social media icons on your edX profile`" text in the Social Media Links section.)
Now:
Compare to the Social Media Links section:
And (just in case) what spacing looks like with the error displayed:
MICROBA-487
=> MICROBA-487 Fix legal text spacing on demographics section

src/id-verification/IdVerificationContext.jsx, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/panels/ReviewRequirementsPanel.jsx, src/id-verification/panels/SubmittedPanel.jsx
[MST-328](https://openedx.atlassian.net/browse/MST-328)
Events that are being collected:
- User enters the flow
- Camera access is denied by the user
- Camera access is unavailable
- User changes their account name to match their ID
- User successfully submits their photos
Caught a couple instances where there was still hardcoded text, so made those i18n compatible and rolled them into this PR as well.
=> Add tracking log events to IDV

src/id-verification/Camera.jsx, src/id-verification/ExistingRequest.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/_id-verification.scss, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/panels/ReviewRequirementsPanel.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx
[MST-353](https://openedx.atlassian.net/browse/MST-353)
Changes addressed with this PR:
- Aria-levels added to headings
- Title changes based on state
---
---
---
---
- 'Next' button comes after FAQ, rather than before
- 'Retake Photo' button changed to Paragon outline variant
- Titles updated to 'Take a Photo of Yourself' and 'Take a Photo of Your ID'
---
---
- Redesigned to use explicit 'yes' or 'no' radio buttons
- 'Name on ID' changed to 'Account Name'
---
---
---
- Buttons updated to Paragon outline variant
- 'Confirm' changed to 'Submit'
---
---
- Updated with a relevant message regarding account activation.
- CTA button fixed to include text.
---
---
=> Add i18n and UX improvements to IDV

src/id-verification/CameraHelp.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/_id-verification.scss, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/IdContextPanel.jsx, src/id-verification/panels/PortraitPhotoContextPanel.jsx, src/id-verification/panels/ReviewRequirementsPanel.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx
[MST-353](https://openedx.atlassian.net/browse/MST-353)
Part one of this ticket can be found in this earlier PR: https://github.com/edx/frontend-app-account/pull/289
- "Tips" pages now include collapsible FAQs
- Text has been updated to correspond to either portrait help or ID help
- Consistent styling adding to card component
---
---
- If the user has a blank account name, the radio button options are disabled and they must enter a name before continuing.
---
---
=> [MST-353] IDV a11y and UX improvements

src/account-settings/data/service.js, src/account-settings/demographics/data/utils.js
We were making an extra call to the LMS when making a PATCH to the
demographics service which we don't need to do.
The keys for demographics fields we not being removed from the
accountSettings object properly, which made them be seen as changes,
which triggered the call to the LMS. I've added a constant
DEMOGRAPHICS_FIELDS that keys out those fields, removing the call.
=> Fix extra call to LMS when PATCHing demographics

src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx, src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx, src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx
Tests added for functionality added with [MST-353](https://openedx.atlassian.net/browse/MST-353). (radio + next buttons are disabled if the learner has a blank account name)
Also covered routing functionality on the summary panel.
=> Add tests for new IDV functionality

src/id-verification/Camera.jsx
Some users appear to be using hardware that is generating photos up to 10MB+ in size.  LMS can only accept 10MB requests.
This limits the photo to 720p which will produce files ~500kB in size.
I've tested this with multiple camera setups and it appears to correctly limit the devices.
=> Limit camera to 720p

package-lock.json, package.json, src/id-verification/IdVerification.messages.js, src/id-verification/panels/EnableCameraDirectionsPanel.jsx, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx
@edx/masters-devs-cosmonauts @wittjeff 
Added browser specific instructions for enabling camera access if it has been detected that camera access has been denied. 
For Chrome:
For Safari:
For Firefox:
=> Added instructions for camera permissions

src/id-verification/CameraHelpWithUpload.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/ImageFileUpload.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
These changes allow learners to upload a photo of their ID rather than taking a photo with their device's camera. This option to upload is contained by a collapsible component on the summary page.
This is what a user will see on the ID image capture page (no changes):
This is what a user will see once they reach the summary page:
When they open the collapsible component:
When they upload an image:
=> Added option for ID image upload

src/id-verification/panels/BasePanel.jsx
Added the ref as a dependency for the useEffect call in order to ensure that useEffect will be called any time the heading is updated.
I don't think a unit test is necessary for this because it can be confirmed by visually testing across all of the panels.
=> Fixed HTML element focus

src/logistration/data/service.js
getHttpclient() returns unauthenticated client. We need authenticated API for the backend POST request. Using getAuthenticatedHttpClient would return authenticated client.
VAN-8
=> fixed csrf verification issue

src/id-verification/Camera.jsx
There are a few learners that are still encountering file size errors when attempting to submit their ID verification. My understanding is that when access to their camera is requested with an ideal resolution and facing mode, the request for that resolution or facing mode is rejected and it falls back to the default resolution and facing mode.
Because of this, additional logic should be added to ensure that if the camera resolution will result in an image with too high of a resolution, there is additional processing done in order to decrease the resolution and therefore decrease the file size.
=> Added logic for adjusting image resolution

src/id-verification/Camera.jsx
This adds the `playsInline` attribute to the video element displayed by the Camera. This prevents the video element from "popping out" into fullscreen mode on iOS Safari. This was tested with iOS 13.1.3.
Old Behavior
Note that the image that is displayed when the video player is closed is the only image that can be taken with the camera, no matter where the camera is pointing.
New Behavior
=> add playsInline attribute to video element to ensure it does not pop out into full screen video on iOS Safari

src/id-verification/CameraHelpWithUpload.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/ImageFileUpload.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
There was no file size limit for uploading an ID image. Error messaging has been added to alert users if they have attempted to upload a file that is larger than 10MB. This has been tested manually.
There was also no feedback if there was an IDV submission error, so users were stuck on a screen with a loading spinner. I have added error messaging to alert a user if there was a submission error. I added a test for this.
=> Added error messaging for image upload and idv submission

src/id-verification/Camera.jsx
**Note:** Safari users are still limited to 480p as it doesn't handle the face detection feature correctly.
=> Increase camera resolution to 1080p for ID verification

src/id-verification/Camera.jsx
Requesting a specific resolution wasn't working consistently across browsers, and it also impacted face detection features on Firefox. 
The camera will request a lower access, but then increase the resolution of the captured photo. This increase will only occur if the video resolution was originally set at 640x480.
I tested on Chrome that the image produced actually has an increased resolution. Without these changes, the size of an image would be approximately 500KB. With these changes, the image has a size of about 1.5MB. 
I'm not sure if this will fix the camera access, but I think it is a step in the right direction.
=> Remove browser based resolution

src/id-verification/Camera.jsx, src/id-verification/IdVerificationContext.jsx
I think that camera access is not being supported on certain devices because the requested constraints change on each of the panels that request the camera (enabling camera access, portrait photo, and ID photo). 
Overall, I think that camera access should be handled better throughout the flow, but I want to test this out first to see if having active streams is causing the problem.
=> Ensure that first stream is stopped

src/id-verification/data/service.js, src/id-verification/panels/SubmittedPanel.jsx, src/id-verification/tests/panels/SubmittedPanel.test.jsx
The course key is being parsed incorrectly, leading to 400 errors. This is a temporary fix while we investigate the solution.
=> Remove use of course key temporarily

src/id-verification/IdVerificationPage.jsx, src/id-verification/tests/IdVerificationPage.test.jsx
[MST-567](https://openedx.atlassian.net/browse/MST-567)
Related to https://github.com/edx/edx-platform/pull/25845 and https://github.com/edx/ecommerce/pull/3284
This addition decodes the `course_id` query string passed into the IDV flow, allowing special characters like `+`.
=> [MST-567] Allow decoding of query string in IDV flow

src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/ReviewRequirementsPanel.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx, src/id-verification/tests/panels/ReviewRequirementsPanel.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
[MST-535](https://openedx.atlassian.net/browse/MST-535)
- Currently, if a learner's profile fields are locked due to SSO, and they attempt to change their name during the IDV flow, they will encounter an error upon submitting. This change implements several warnings for these learners before IDV submission, and prevents them from attempting to change their name manually.
- Also fixed a bug where the name change field was resetting to to original name when cleared.
---
---
---
=> [MST-535] Prevent IDV name change if name is managed by a third party

src/id-verification/CollapsibleImageHelp.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/IdVerificationPage.jsx, src/id-verification/ImageFileUpload.jsx, src/id-verification/panels/ChooseModePanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx, src/id-verification/routing-utilities.js, src/id-verification/tests/CollapsibleImageHelp.test.jsx, src/id-verification/tests/panels/ChooseModePanel.test.jsx, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx, src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx, src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx
These changes allow a user in an experiment to choose if they would like to upload photos instead of using their camera to submit IDV photos. I've introduced a new panel here which allows them to initially make that choice: 
If they select that they would like to upload photos, they are immediately taken to this panel, bypassing the context panel that is usually shown before the photo capture pages: 
As you can see on the above image, the user also has the option to switch between camera/upload mode throughout the IDV flow. The placement of the toggle button to switch between modes was suggested by Kevin on UX. If they choose to use their camera, they will see this panel: 
I've also added additional routing to ensure that if a user tries to toggle to the camera mode, but hasn't enabled …
=> MST-652: Add option to upload photos if user is in experiment

src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
If a user is part of an A/B experiment for IDV, they will not be shown the option to upload an ID photo on the summary panel. 
The current experience looks like this: 
The experiment experience will look like this:
=> Remove option to upload if user is in experiment

src/id-verification/CameraHelp.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/tests/panels/IdContextPanel.test.jsx, src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx
When a user goes through the IDV experiment, they should have additional help text on the photo context panels explaining that they can also upload photos.
This is what each of the photo context panels will look like in the experiment:
=> Added upload help text to photo context panels

src/id-verification/CameraHelpWithUpload.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/ImageFileUpload.jsx, src/id-verification/SupportedMediaTypes.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
[MST-718](https://openedx.atlassian.net/browse/MST-718)
As an extra measure to prevent the user from uploading unsupported file types such as `.pdf`, this adds JS validation on top of the `accept` attribute.
=> [MST-718] Add extra validation to IDV image upload

src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/routing-utilities.js, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx
If users are part of the A/B experiment for photo upload on the IDV flow, they should be allowed to continue with photo upload if they deny camera access or camera access is unsupported. If they have already denied camera access, they will not be allowed to switch between upload and photo capture mode throughout the flow. Instead the user will only be allowed to complete the flow by uploading photos from their device.
If a user is part of the experiment and has denied/unsupported camera access they will see this panel: 
If they continue with upload, they will see this panel (that does not give them access to switch to photo capture mode):
=> feat: Allow users in experiment to continue with upload if no camera access

src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/routing-utilities.js, src/id-verification/tests/panels/ChooseModePanel.test.jsx, src/id-verification/tests/panels/IdContextPanel.test.jsx, src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx, src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx, src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx
[MST-717](https://openedx.atlassian.net/browse/MST-717)
The new reroutes introduced in the current A/B test override the summary panel reroute, resulting in incorrect behavior. This fix ensures that, if a user has reached the summary panel once, they are properly rerouted from the camera/upload panels after going back to retake or re-upload their photos.
=> [MST-717] Reroute user to summary panel in A/B test

src/id-verification/CollapsibleImageHelp.jsx, src/id-verification/panels/ChooseModePanel.jsx
Add event tracking for initial choice in photo mode, and additional events when a user toggles between modes on the photo capture pages
=> MST IDV Experiment Event Tracking

src/id-verification/Camera.jsx, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/ImageFileUpload.jsx, src/id-verification/data/service.js, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx, src/id-verification/tests/Camera.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
In addition to the other data being collected for the IDV experiment, we would also like to know exactly which mode a learner used to submit photos. This data is then used in a segment tracking event, as seen in this PR: https://github.com/edx/edx-platform/pull/27349
=> Add additional post parameters to track photo modes

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/delete-account/BeforeProceedingBanner.jsx, src/account-settings/delete-account/ConfirmationModal.jsx, src/account-settings/delete-account/DeleteAccount.jsx, src/account-settings/delete-account/PrintingInstructions.jsx, src/account-settings/delete-account/__snapshots__/ConfirmationModal.test.jsx.snap, src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap, src/account-settings/delete-account/messages.js, src/account-settings/demographics/DemographicsSection.jsx, src/account-settings/demographics/DemographicsSection.messages.jsx, src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap, src/account-settings/third-party-auth/ThirdPartyAuth.jsx, src/id-verification/CameraHelp.jsx, src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationPage.jsx, src/id-verification/panels/ReviewRequirementsPanel.jsx, src/id-verification/panels/SummaryPanel.jsx
This is most easily reviewed commit-by-commit. 
You can read about it in the comments, but it includes a bit of a hack to show alternate messages if the SITE_NAME is set to 'edX'.  This is because we have no way of supplying site-specific strings today, but needed to make the defaults Open edX-friendly.
Later, if we can find a way to include site-specific stuff, we could undo this.  It's all annotated as TODOs.
Will cherry-pick to lilac.master once we get it in.
=> fix: Resolving i18n violations, hard-coded edx.org-specific strings

renovate.json
This repo was allowing both patch/minor updates of Paragon, but I've opened that up a bit with this PR.  This is based on similar config we've used in other repositories.
It loses the "stability days" that were here, but I don't think we need that for patch/minor updates.
=> chore: let renovate be more liberal about what it merges

renovate.json
to avoid bumping the major version, besides linters and testers.
=> build(renovate): be more selective about automerging devDependencies

package-lock.json, package.json, src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap, src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
The snapshots changed because Hyperlink changed its 'external link' icon from font-awesome to SVG and also added some CSS classes.
=> fix: upgrade frontend-build to v7 and paragon to v16

src/account-settings/data/service.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx
If the Verified Name feature is turned on, and the user do have a VerifiedName, use that name on the Account Name Check page of the IDV flow instead of account profile name
=> feat: Update IDV workflow to use the VerifiedName

src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx
MST-990, we should fix the problem where the ID name error message still show up with Account name filled in or Verified name filled in.
=> fix: Should not display error message when the account name matches the ID name

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/EditableField.jsx, src/account-settings/_style.scss, src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
[MST-957](https://openedx.atlassian.net/browse/MST-957)
When the VerifiedName is in pending status, 
update the editable field for VerifiedName to be not editable,
and show yellow warning icon. See screenshot below
=> feat: Make VerifiedName not editable and show proper icon when the Name is in pending status

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx
If a learner requests a profile name change or verified name change that requires ID verification, their ID verification submission may be rejected. This code change adds a dismissible error alert to the Account Settings page informing the learner of the failure and redirecting them to a help article about ID verification failures. The local storage key used to determine whether to show the alert or not uses the created time of the name verification object to ensure that subsequent ID verification failures still trigger this alert, even for the same name.
MST-954 (https://openedx.atlassian.net/browse/MST-954)
I'll be working on a code change to revert to restoring the previous name affirmation state.
=> feat: Add Dismissible Alert Informing Learner of Failed Name Verification

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx
If a learner has a submitted verified name change, we should alert them of that submitted name change. In addition to displaying an alert, we also want to make both the verified name and full name fields grayed-out and uneditable. The help text for each of those fields should also be updated.
=> feat: add alert and correct messaging for submitted verified name

src/account-settings/AccountSettingsPage.jsx, src/account-settings/data/selectors.js
This code change fixes a bug where the verified name field was not editable. This was due to the fact that the verified name was not wired up to the Redux store, so draft verified names were not stored in the Redux store.
=> fix: Fix Broken Editing of Verified Name Field

src/account-settings/data/service.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx
The verified_name endpoint provides is_enabled only if a name exists and otherwise 404s, so we have to request the enabled flag separately through the new endpoint to make sure we get it.
Validated on local build with an approved IDV and name affirmation on and off.
MST-1026
=> feat: if verified name is on, we can redo ID verification

src/account-settings/AccountSettingsPage.jsx, src/account-settings/data/reducers.js, src/account-settings/data/sagas.js, src/account-settings/data/selectors.js, src/account-settings/data/service.js, src/account-settings/name-change/NameChange.jsx, src/account-settings/name-change/data/actions.js, src/account-settings/name-change/data/reducers.js, src/account-settings/name-change/data/sagas.js, src/account-settings/name-change/data/service.js, src/account-settings/name-change/index.js, src/account-settings/name-change/messages.js, src/account-settings/name-change/test/NameChange.test.jsx
[MST-803](https://openedx.atlassian.net/browse/MST-803)
If name change requires ID verification, display a modal that prompts the user to enter their ID name. On submit, this creates a pending name change + a verified name with the given names, and directs the user to the IDV flow.
=> [MST-803] Add name change modal

src/account-settings/data/selectors.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/IdVerificationPage.jsx, src/id-verification/VerifiedNameContext.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx, src/id-verification/tests/IdVerificationPage.test.jsx, src/id-verification/tests/VerifiedNameContextProvider.test.jsx, src/tests/utils.test.js, src/utils.js
[MST-1016](https://openedx.atlassian.net/browse/MST-1016)
If a learner has a pending or approved verified name, the most recent should take precedence over the profile name on the GetNameIdPanel during the "Account Name Check". If the learner has no pending or approved verified names, then the learner's profile name should be used instead.
=> feat: include pending or approved verified names in the name field if they exist

src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
MST-1059: https://openedx.atlassian.net/browse/MST-1059
This code change changes how the full_name field is included in the form data sent during IDV submission.
Before, full_name was only included in the form data when the learner entered a different name in the GetNameIdPanel than what was displayed to them as the default (i.e. their full name on their profile). If a full_name was provided in the request, the server would use the supplied full_name when creating the IDV record and would update the learner's full name on their profile accordingly. If a full_name was not provided in the request, then the server would fall back to the current full name on their profile when creating the IDV record and no change to the full name on their profile would occur.
With the introduction of the …
=> feat: send nameOnAccount as full_name with all IDV submissions when learner has no name change and verified name feature is enabled

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/EditableField.jsx, src/account-settings/certificate-preference/CertificatePreference.jsx, src/account-settings/data/actions.js, src/account-settings/data/reducers.js, src/account-settings/data/sagas.js, src/account-settings/data/selectors.js, src/account-settings/data/service.js, src/account-settings/name-change/NameChange.jsx, src/account-settings/name-change/data/actions.js, src/account-settings/name-change/data/sagas.js, src/account-settings/name-change/test/NameChange.test.jsx
[MST-1029](https://openedx.atlassian.net/browse/MST-1029)
1. Update the NameChange modal to function with both the profile and verified name fields. The UX is effectively the same for updating either name, if you enter verified name into the form it will just prefill the input on the last panel.
2. Was running into some issues were verifiedName in the form was bound to the verifiedName model object. This was causing updating the form to override the object with a string. I did some refactoring to move state values that aren't reflected in the form itself out of the formData object.
There's one functional change as a result of this that could be up for discussion. If the user has a previously approved verified name that name gets pre-populated into the form when changing your profile name. …
=> submit verified name change

src/account-settings/AccountSettingsPage.jsx
Found while testing MST-1029 on stage. This property defaults to {} but the api response could cause it to be null. This only happens if the flag is on however so no impact if this were to go out.
=> fix: null check mostRecentVerifiedName

src/id-verification/IdVerification.messages.js, src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx
[MST-797](https://openedx.atlassian.net/browse/MST-797)
Update IDV instructions to be more explicit about the need for a photo identification card, and provide a few more examples.
---
---
---
---
=> [MST-797] Update IDV instructions

src/account-settings/AccountSettingsPage.jsx, src/account-settings/certificate-preference/CertificatePreference.jsx, src/account-settings/certificate-preference/test/CertificatePreference.test.jsx, src/account-settings/data/selectors.js
Fixed a bug that incorrectly rendered the certificate preference checkbox upon each page render. The bug caused 
* the checkboxes to both be selected at the same time
* the checkbox to always be selected for the profile name
* wouldn't allow the proper UI changes upon saving a verified name (i.e. save button wouldn't have a spinner, form wouldn't close)
The checkbox selection works correctly now, and the save button for the verified name field also works as expected.
=> fix: Checkbox incorrectly tied to profile name

src/account-settings/data/selectors.js
[MST-1073](https://openedx.atlassian.net/browse/MST-1073)
When a learner's most recent Verified Name is in the pending state, we should display their most recent approved Verified Name. If such a Verified Name does not exist, do not display any Verified Name. In either case, do not disable or gray out either the Full name or Verified name fields.
This change is being made because we do not want to prevent a learner from editing the Verified name field if their most recent entry is pending. An entry remains in the pending state when a learner has created a Verified name by changing their name on the Account Settings page but has not followed through with submitting their IDV.
=> fix: Display Last Approved Verified Name When Most Recent Verified Name is Pending

src/account-settings/AccountSettingsPage.jsx
Current behavior:
- Learner changes their name, is prompted to complete IDV, and it is approved
- Learner dismisses the "approved" alert on their account settings page
- Learner submits another name change, and it is approved
- The "approved" alert will not appear again on the account settings page, because the local storage value determining whether the alert has been dismissed still persists in the browser
Behavior with fix:
- Learner changes their name, is prompted to complete IDV, and it is approved
- Learner dismisses the "approved" alert on their account settings page
- Learner submits another name change, and it is approved
- New "approved" alert is visible on their account settings page
=> fix: approved alert should appear for subsequent approved attempts

src/account-settings/data/sagas.js
[MST-1089](https://openedx.atlassian.net/browse/MST-1089)
Fixes an issue where the name change modal would trigger for any error related to the "full name" field, rather than just when the name change requires ID verification.
This is the relevant check on the backend: https://github.com/edx/edx-platform/blob/0935b5c51fa4115caa6d6d98b0ef65fea4fcdec1/openedx/core/djangoapps/user_api/accounts/api.py#L239
=> [MST-1089] Only display name change modal when backend requires verification

jest.config.js, src/id-verification/IdVerification.messages.js, src/id-verification/_id-verification.scss, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/AccessBlocked.test.jsx, src/id-verification/tests/Camera.test.jsx, src/id-verification/tests/CollapsibleImageHelp.test.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx, src/id-verification/tests/VerifiedNameContextProvider.test.jsx, src/id-verification/tests/panels/ChooseModePanel.test.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx, src/id-verification/tests/panels/IdContextPanel.test.jsx, src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx, src/id-verification/tests/panels/SubmittedPanel.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx, src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx, src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx, src/setupTest.js
[MST-1065](https://openedx.atlassian.net/browse/MST-1065)
When the Name Affirmation feature is enabled, a few panels in the IDV workflow should have different copy to reflect the changes associated with Name Affirmation. This is because entering a new during the IDV flow (GetNameIdPanel) will no longer modify the learner's "Account Name". Furthermore, "Account Name" is an ambiguous term; it's not clear that it refers to the learner's full name on their profile. These copy changes make the panel more generic and remove details about name changes. The SummaryPanel also has a minor copy change to change "Account Name" to "Name".
These code changes also include some UI changes.
**Before:**
**After:**
=> MST-1065: Add Copy and UI Treatment for Name Affirmation When Enabled 

src/hooks.js, src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/VerifiedNameContext.jsx, src/tests/hooks.test.jsx
[MST-1099](https://openedx.atlassian.net/browse/MST-1099)
Due to a bug in the way the canVerify React state is being set, when the verified name feature is enabled, the code inconsistently loads either the AccessBlocked panel or the ReviewRequirementsPanel when the learner should be allowed to verify. If the learner is ineligible to complete IDV due to their IDV history (e.g. they already have an approved IDV), and the verified name feature is enabled, the learner should be able to verify and should not see the AccessBlocked panel. This code change fixes this bug.
This code change also fixes flickering that occurs when IDV is loading. This code change also includes some copy fixes.
=> [MST-1099] Fix Flickering in IDV Panel Loading and Inconsistent Panel Loading

src/account-settings/AccountSettingsPage.jsx, src/account-settings/certificate-preference/CertificatePreference.jsx, src/account-settings/certificate-preference/test/CertificatePreference.test.jsx, src/account-settings/data/reducers.js, src/account-settings/data/selectors.js, src/account-settings/data/service.js, src/id-verification/IdVerification.messages.js, src/id-verification/IdVerificationContextProvider.jsx, src/id-verification/VerifiedNameContext.jsx, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/SummaryPanel.jsx, src/id-verification/tests/IdVerificationContextProvider.test.jsx, src/id-verification/tests/VerifiedNameContextProvider.test.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx, src/id-verification/tests/panels/SummaryPanel.test.jsx
feat: Remove Use of Verified Name Enabled Flag
The VERIFIED_NAME_FLAG was added as part https://github.com/edx/edx-name-affirmation/pull/12, [MST-801](https://openedx.atlassian.net/browse/MST-801) in order to control the release of the Verified Name project. It was used for a phased roll out by percentage of users.
The release reached a percentage of 50% before it was observed that, due to the way percentage roll out works in django-waffle, the code to create or update VerifiedName records was not working properly. The code was written such that any change to a SoftwareSecurePhotoVerification model instance sent a signal, which was received and handled by the Name Affirmation application. If the VERIFIED_NAME_FLAG was on for the requesting user, a Celery task was launched from the Name …
=> feat: Remove Use of Verified Name Enabled Flag

src/id-verification/panels/TakeIdPhotoPanel.jsx, src/id-verification/panels/TakePortraitPhotoPanel.jsx
https://openedx.atlassian.net/browse/MST-1075
Before this fix, focus would return to the heading when the user takes an IDV photo, causing the scrollbar to jump to the top of the page. The focus should remain on the photo capture button.
=> [MST-1075] Prevent focus jump when taking photo

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx
If a verified name attempt is created by proctoring, we should 1) not show an alert to the user and 2) update the help text for the full name and verified name fields to clarify why the fields are being updated. Maddie from support gave me the copy changes for the help text.
I've included the four scenarios where language is updated in the help text. The language is dependent on the status of the verified name, if the name was created by proctoring, and if the name has been chosen to appear on a certificate.
**Status is submitted (through proctoring), full name should appear on certs:**
**Status is submitted (through proctoring), verified name should appear on certs:**
**Status is verified (through proctoring), verified name should appear on certs:**
**Status is verified (through …
=> fix: remove alert and update language if verified name comes from proctored exam attempt

Makefile
- New Transifex client needs `languages` instead of `language` as a parameter so updating the command to run the translation job successfully.
=> build: update pull_translations command

.github/workflows/ci.yml, package-lock.json
We're moving to Node 16 and it uses npm 8. Dependencies were installed with npm 6 in last PR merged in this package due to which package-lock file again became incompatible for Node 16 so updating it again.
=> Install Dependencies using Npm 8

.github/workflows/ci.yml, Makefile, package-lock.json, package.json
* Removes custom `browserslist` configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
* Removes `is-es5` check in CI since ES5 was only needed for IE 11 support which is dropped. The supported browsers defined by the shared configuration all [natively support ES6](https://caniuse.com/?search=es6).
This change reduces the resultant asset bundle size.
=> build: use shared browserslist configuration

package-lock.json
- Bumped versions for minimatch, recursive-readdir & loader-utils in package-lock
=> refactor: bumped minimatch, recursive-readdir & loader-utils

src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/DOBForm.jsx
Users should be forced to update the DOB form before being allowed to submit. Submission is blocked unless the user picks a valid month and year from each drop down, even in the case where the user re-selects the default "Select month" or "Select year" options.
=> fix: prevent users from submitting DOB without update

src/account-settings/BetaLanguageBanner.jsx, src/account-settings/site-language/constants.js
**Ticket**
[Learner Running into "Unexpected Error" when he tried to access Account Settings Page](https://2u-internal.atlassian.net/browse/BOM-3487)
**Related Issue**
[Page crashes when dark lang is set to partially supported language](https://github.com/openedx/frontend-app-account/issues/701)
=> fix: added language codes to support affected languages

package-lock.json, package.json
Reverted `frontend-platform `version since v4 is causing dependency issues & we are unable to update the `edx-internal` until `header-edx` PR is merged which is dependent on enterprise node v18 upgrade (currently blocked due to enterprise lerna issue)
=> refactor: reverted platform to v2.6 to avoid dependency issues

Makefile, package-lock.json, package.json, src/account-settings/delete-account/DeleteAccount.test.jsx, src/i18n/index.js, src/id-verification/tests/IdVerificationPage.test.jsx, src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx, src/index.jsx
Changes:
-------
- Bump frontend-platform to bring intl-imports.js script
- Move all i18n imports into `src/i18n/index.js` so intl-imports.js can override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
- Fixed lint rules for frontend-platform@4.1.0
Testing
-------
<kbd>![image](https://user-images.githubusercontent.com/645156/232773201-6bb609db-01a3-4f55-b465-b653e322d1b4.png)</kbd>
</details> 
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification). …
=> feat: use `atlas` in `make pull_translations`

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/JumpNav.jsx, src/account-settings/test/__snapshots__/JumpNav.test.jsx.snap, src/data/reducers.js, src/index.jsx, src/index.scss, src/notification-preferences/NotificationCourses.jsx, src/notification-preferences/NotificationPreferenceGroup.jsx, src/notification-preferences/NotificationPreferenceRow.jsx, src/notification-preferences/NotificationPreferences.jsx, src/notification-preferences/ToggleSwitch.jsx, src/notification-preferences/data/actions.js, src/notification-preferences/data/reducers.js, src/notification-preferences/data/selectors.js, src/notification-preferences/data/service.js, src/notification-preferences/data/thunks.js, src/notification-preferences/messages.js
Added Notification Preferences UI components.
- JumpNav component will have a new option
- Created new page that will all the active courses in which user is enrolled in
- When a user will select a course, he/she will be redirected to preferences page of the selected course  
Tests will be added after api integration
=> feat: added notification preference ui

src/notification-preferences/NotificationPreferences.test.jsx, src/notification-preferences/data/reducers.js, src/notification-preferences/data/reducers.test.js, src/notification-preferences/data/selectors.js, src/notification-preferences/data/thunks.js, src/notification-preferences/messages.js
- Make the core notification toggle disable according to nonEditable.
=> refactor: update notEditable to nonEditable in notification preferences

src/account-settings/AccountSettingsPage.jsx, src/account-settings/JumpNav.jsx, src/account-settings/test/JumpNav.test.jsx, src/index.jsx, src/notification-preferences/data/reducers.js, src/notification-preferences/data/selectors.js, src/notification-preferences/data/thunks.js
- Hide and show the notification preferences according to the `showPreferences` flag.
=> feat: implement showPreferences flag in notification preferences

src/notification-preferences/NotificationPreferenceRow.jsx, src/notification-preferences/data/reducers.js, src/notification-preferences/data/thunks.js
[INF-1086](https://2u-internal.atlassian.net/browse/INF-1086)
Preferences toggles sometimes have a weird behaviour. 
1. I turned off both toggles the questions toggle turned back on after a few seconds.
2. When it turned it off, the discussions toggle turned back on. 
Solution: Disabled all buttons until the api patch request completes.
=> fix: fixed preferences toggle unpredictable behavior 

package-lock.json, package.json
This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
=> fix(deps): update dependency @edx/frontend-platform to v5.5.4

src/notification-preferences/NotificationCourses.jsx, src/notification-preferences/NotificationPreferenceApp.jsx, src/notification-preferences/NotificationPreferenceRow.jsx, src/notification-preferences/NotificationPreferences.jsx, src/notification-preferences/data/constants.js, src/notification-preferences/messages.js
**[INF-1120](https://2u-internal.atlassian.net/browse/INF-1120)**
- Removed extra spaces from notification preferences module messages.
- Removed disable eslint and refactored code accordingly.
- Create a constant for notification channels and use it accordingly.
=> refactor: removed disable eslint and created channels constant

src/notification-preferences/NotificationPreferenceRow.jsx, src/notification-preferences/data/reducers.js, src/notification-preferences/data/reducers.test.js, src/notification-preferences/data/selectors.js
[INF-1086](https://2u-internal.atlassian.net/browse/INF-1086)
Removed extra loading effect of spinner while updating the notification preferences.
**Screenshots**
**Before**
**After**
=> fix: removed extra loader while updating preferences

src/account-settings/site-language/constants.js
Started researching into this issues because of this issue:
https://github.com/openedx/wg-build-test-release/issues/267 
For a few languages we have multiple files:
missing translation:
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/de.json
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/it.json
proper translation:
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/de_DE.json
- https://github.com/openedx/frontend-app-account/blob/open-release/palm.master/src/i18n/messages/it_IT.json
This PR adds the correct one in the options
=> fix: Correction to the language code for Português, Italian and German

src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/data/constants.js
When user selects "Other Education" and clicks save - error occurs.
It's caused by the wrong API call payload value `'o'`
Fix: use the `'other'` payload value instead (the valid one).
Port from: [palm.master](https://github.com/openedx/frontend-app-account/pull/881)
Related: [master](https://github.com/openedx/frontend-app-account/pull/925)
=> fix: error when trying to save 'other education'

src/account-settings/EditableField.jsx
This pull request contains minor fixes for when a user pastes a very long link into the social media links field.
In this case, the links break the page and add horizontal scrolling.
PR to the open-release/palm.master branch: https://github.com/openedx/frontend-app-account/pull/915
=> fix: trim long text in links in the social networks block

src/index.jsx
Added the missing 'ID' parameter for the main section. When we want to use keyboard navigation through the page, the first anchor we encounter on the account page is 'Skip to main content,' which allows us to skip the header and move to the content area. However, this anchor is linked to the #main ID, which is missing in the main section.
Before fix:
https://github.com/openedx/frontend-app-account/assets/19806032/78bb15d0-39f9-4997-a397-59883fc75765
After:
https://github.com/openedx/frontend-app-account/assets/19806032/4479e948-af9f-45be-8a3e-a6e81eb99db1
=> fix: Add ID attribute to the main content

src/notification-preferences/NotificationPreferenceApp.jsx
[INF-1164](https://2u-internal.atlassian.net/browse/INF-1164)
The toggle for App Level Preferences is disabled during an ongoing API call.
**Screenshot**
https://www.loom.com/share/7c722f2f0b034458b2232b60f5183d45?sid=c37aa2a2-f811-4fb3-b069-131978ef3c7a
=> fix: app level toggle is now disabled during api call

src/account-settings/EditableSelectField.jsx, src/account-settings/data/selectors.test.js, src/account-settings/test/EditableSelectField.test.jsx, src/account-settings/test/__snapshots__/EditableSelectField.test.jsx.snap
An error was found when selecting a timezone in the user account.
In this [PR](https://github.com/openedx/frontend-app-account/pull/27), a time zone selection was added.
Then the select field was rewritten in [PR](https://github.com/openedx/frontend-app-account/pull/612). (Paragon form component deprecations)
However, these changes have broken the time zone selection field.
=> fix: Fixed the display of the selection of available time zones

src/account-settings/EditableSelectField.jsx, src/account-settings/data/selectors.test.js, src/account-settings/test/EditableSelectField.test.jsx, src/account-settings/test/__snapshots__/EditableSelectField.test.jsx.snap
Backport from the [master](https://github.com/openedx/frontend-app-account/pull/896).
An error was found when selecting a timezone in the user account.
In this [PR](https://github.com/openedx/frontend-app-account/pull/27), a time zone selection was added.
Then the select field was rewritten in [PR](https://github.com/openedx/frontend-app-account/pull/612). (Paragon form component deprecations)
However, these changes have broken the time zone selection field.
=> fix: Fixed the display of the selection of available time zones (for Quince)

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/certificate-preference/test/CertificatePreference.test.jsx, src/account-settings/data/actions.js, src/account-settings/data/constants.js, src/account-settings/data/sagas.js, src/account-settings/data/selectors.js, src/account-settings/data/selectors.test.js, src/account-settings/test/AccountSettingsPage.test.jsx, src/account-settings/test/mockData.js
I have added a work experience field that will be shown on the front-end account setting page.  
https://2u-internal.atlassian.net/browse/VAN-1790
###
How Has This Been Tested?
you can add settings in django admin site configuration like this 
```
"extended_profile_fields": [
"work_experience"
],
"EXTRA_FIELD_OPTIONS": {
"work_experience": [
"0",
"1",
"2",
"3",
"4",
"5",
"6",
"7",
"8",
"9",
"10+"
]
}
```
and the field will be shown of auth account settings. You can add or edit the field.
=> feat: add  work experience field

src/account-settings/EditableSelectField.jsx, src/account-settings/test/EditableSelectField.test.jsx
Backport from the [master](https://github.com/openedx/frontend-app-account/pull/896).
An error was found when selecting a timezone in the user account.
In this [PR](https://github.com/openedx/frontend-app-account/pull/27), a time zone selection was added.
Then the select field was rewritten in [PR](https://github.com/openedx/frontend-app-account/pull/612). (Paragon form component deprecations)
However, these changes have broken the time zone selection field.
=> fix: Fixed the display of the selection of available time zones (for Palm)

src/notification-preferences/NotificationPreferenceColumn.jsx, src/notification-preferences/NotificationPreferences.test.jsx, src/notification-preferences/NotificationTypes.jsx, src/notification-preferences/data/thunks.js
[INF-1283](https://2u-internal.atlassian.net/browse/INF-1283)
We've removed core notifications from the frontend, as the Updates app currently doesn't include any core notifications. We've updated the logic on the frontend to verify if there are any core notifications available for an app. If not, we're no longer displaying core preferences for that notification app.
=> fix: core notification is now not visible under updates

package-lock.json, package.json
The previous version of `frontend-slot-footer` had a peer dependency of `^14.0.0`, which caused problems for some methods of installing forked footers. This updates to a version of `frontend-slot-footer` that allows for *any* version of `frontend-component-footer` in the peer dependency.
=> fix: use `frontend-slot-footer` that supports all footer versions

src/notification-preferences/EmailCadences.jsx
[INF-1389](https://2u-internal.atlassian.net/browse/INF-1389)
In notification preference view, when a patch call is initiated to updated, all of the toggles and dropdowns must be disabled. 
**Solution**
Disabled dropdowns while api response is in pending state
=> fix: disabled email cadence dropdown while api is pending

src/index.scss, src/notification-preferences/NotificationPreferenceApp.jsx, src/notification-preferences/NotificationPreferenceColumn.jsx, src/notification-preferences/NotificationPreferences.jsx, src/notification-preferences/NotificationPreferences.test.jsx, src/notification-preferences/NotificationTypes.jsx, src/notification-preferences/data/actions.js, src/notification-preferences/data/selectors.js, src/notification-preferences/data/service.js, src/notification-preferences/data/thunks.js, src/notification-preferences/messages.js
[INF-1415](https://2u-internal.atlassian.net/browse/INF-1415)
Remove app level toggles from preferences UI in accounts MFE
ACs
1. App-level toggles from preferences UI in accounts MFEn should be removed. 
2. Remove Type form each app and move it to top
3. Remove dividers between app
4. Rename core notifications in discussions to Activity notifications
5. Enable core notification toggle that is disabled by default
**Screenshot**
=> feat: removed app level toggles

src/notification-preferences/data/constants.js
Removing `Immediately` from email preference dropdown. It will be added after implementation.
=> temp: removing immediately from email preferences

src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/name-change/messages.js
Just a copy change on the Name Change modal. This is part of the New IDV vendor work https://github.com/openedx/platform-roadmap/issues/367.
Old copy:
> Enter your name as it appears on your unexpired student, work, or government-issued identification card.
New copy:
> Enter your name as it appears on your identification card.
Tested locally.
=> fix: Updated copy change on Name Change modal

src/account-settings/AccountSettingsPage.jsx, src/account-settings/EditableSelectField.jsx, src/account-settings/data/reducers.js, src/account-settings/data/selectors.js
[INF-1567](https://2u-internal.atlassian.net/browse/INF-1567)
- Countries in the `disabledCountries` list will no longer be visible to users in the account settings of other countries, and users will not be able to switch to disabled countries. 
- User with a disabled country selected can change their country to another one. After switching, they cannot select the disabled country again.
- Implemented frontend validation to verify the country against the disabled countries list to prevent invalid country submissions.
For Example, if Russia is on the disabled countries list.
> Other Country Users will not see Russia in the country list as an 
------------------------------------------------------------------------------------------------------------------------
> Russian user will see …
=> feat: added country disabling feature

package-lock.json, package.json, src/account-settings/AccountSettingsPage.jsx, src/account-settings/EditableSelectField.jsx, src/account-settings/data/reducers.js, src/account-settings/data/selectors.js, src/notification-preferences/messages.js
Rebase 2u-main branch with master
=> refactor: sync 2u-main with master

src/account-settings/AccountSettingsPage.jsx
The "Learn more about ID Verification" button that is displayed as part of the failed IDV notification lead to an inaccessible link. The button should be removed to prevent confusion.
* Create a verified name via django admin for your test user, and mark the verified name as rejected
* Load the account settings page and ensure the "Learn more about ID Verification" button is not included in the verified name alert
|Before|After|
|-------|-----|
|<img width="512" alt="verified_name_before" src="https://github.com/user-attachments/assets/ffecce93-f731-4e37-99db-671a58d80a8b">|![Screenshot 2024-10-21 at 2 45 20 PM](https://github.com/user-attachments/assets/3b31bac7-3f83-49e2-80a6-e51a8ece1f40)|
=> feat: remove learn more about IDV button

src/account-settings/site-language/service.js, src/account-settings/third-party-auth/data/service.js
This PR solves a CORS error when calling the endpoints for **Changing Site Language** and **Unlinking the SSO Account**. To resolve this error we simply specify the `Accept: 'application/json'` header in the request.
These are the related issues:
- https://github.com/openedx/frontend-app-account/issues/1052
- https://github.com/openedx/wg-build-test-release/issues/376
The changes have been tested in a local environment with **Tutor v18.1.3**.
1. In your Tutor environment clone the Account MFE with these changes.
2. Create a mount with `tutor mounts add frontend-app-account`
3. Run `tutor dev start -d` to recreate the containers.
4. Inside the Account MFE folder run `npm install`
5. Finally run `tutor dev restart`
1. Go to the **Account Settings** > **Site Preferences**.
2. Click **Edit** …
=> fix: send json accept headers for POST requests

.env, .env.development, .env.test, src/account-settings/delete-account/DeleteAccount.jsx, src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap
[INF-1675](https://2u-internal.atlassian.net/browse/INF-1675)
The Account MFE contains outdated support links that point to http://support.edx.org/ . These links are currently broken as edX has moved their support documentation to  http://help.edx.org/ . Any clicks on the old http://support.edx.org/   URLs are automatically redirecting to the new [http://help.edx.org ](http://help.edx.org/)  domain, which  lead  incorrect or broken pages.
The URLs in the Account MFE are updated to reflect this change.
=> fix: fixed support urls

.eslintignore, Makefile, package-lock.json, package.json, src/account-settings/AccountSettingsPage.jsx
[INF-1709](https://2u-internal.atlassian.net/browse/INF-1709)
- Removed PropType Error
- Removed Translation Error
=> fix: translation and console errors

src/account-settings/AccountSettingsPage.jsx, src/account-settings/AccountSettingsPage.messages.jsx, src/account-settings/delete-account/DeleteAccount.jsx, src/account-settings/delete-account/messages.js
Move cannot delete account inside `DeleteAccount` component
Updated text to `Please note that, for legal and regulatory compliance purposes, account deletion is currently unavailable.`
=> refactor: moved unable to delete into component

src/account-settings/AccountSettingsPage.jsx, src/account-settings/JumpNav.jsx, src/account-settings/test/__snapshots__/JumpNav.test.jsx.snap
This is backport from master https://github.com/openedx/frontend-app-account/pull/994
Our proposal is to modify the width values of jump-nav and content to their state prior to this pull request - https://github.com/openedx/frontend-app-account/pull/784. In this pull request, the width of the jump nav was reduced, and the width of the content was increased. This results in the jump nav appearing very narrow on themes with a maximum container width. Even the phrase "Account Information" does not fit into a single line
After this small fix we'll restore previous state of the columns width, like in Palm
=> feat: Restore jump nav and content width [backport from master]

src/account-settings/AccountSettingsPage.jsx, src/account-settings/JumpNav.jsx, src/account-settings/test/__snapshots__/JumpNav.test.jsx.snap, src/notification-preferences/NotificationSettings.jsx
Updated the notifications preferences section URL which is used on different MFEs to redirect the user to the notifications preferences center.
Old URL: `https://account.edx.org/notifications`
New URL: `https://account.edx.org/#notifications`
=> fix: updated notifications section url

src/notification-preferences/EmailCadences.jsx, src/notification-preferences/NotificationPreferenceColumn.jsx, src/notification-preferences/data/constants.js, src/notification-preferences/data/thunks.js
[INF-1797](https://2u-internal.atlassian.net/browse/INF-1797)
We deprecated the “Never” email frequency for emails a while ago.
However, it is still persisting for people who had selected it before deprecation. Even if someone turns on email notifications toggle, “Never” persists.
**Acceptance Criteria**
Modify UX such that when a person turns on email toggle for a preference from COURSE or ACCOUNT level, the email cadences for that preference should change to “Daily” no matter what it was before (Never/Weekly/Daily).
=> fix: changed frequency from never to daily on email  preference change

src/account-settings/AccountSettingsPage.jsx, src/account-settings/data/actions.js, src/account-settings/data/constants.js, src/account-settings/data/reducers.js, src/account-settings/data/sagas.js, src/account-settings/data/selectors.js, src/account-settings/data/service.js
We are introducing a feature that allows platform administrators to restrict users from selecting one or more countries in Account MFEs.
We retrieved the list of restricted countries by calling the following API:
👉 https://courses.edx.org/user_api/v1/account/registration/
At the same time, we obtained the translated country names using the i18n-iso-countries package.
Once both datasets were available, we filtered out the restricted countries from the translated list and displayed the updated country list in the UI.
=> feat: implemented restricted countries functionalities

src/notification-preferences/data/constants.js, src/notification-preferences/data/thunk.test.js, src/notification-preferences/data/thunks.js
[INF-1797](https://2u-internal.atlassian.net/browse/INF-1797)
We deprecated the “Never” email frequency for emails a while ago.
However, it is still persisting for people who had selected it before deprecation. Even if someone turns on email notifications toggle, “Never” persists.
**Acceptance Criteria**
Modify UX such that when a person turns on email toggle for a preference from COURSE or ACCOUNT level, the email cadences for that preference should change to “Daily” no matter what it was before (Never/Weekly/Daily).
=> fix: fixed course level preference issue

README.rst, src/notification-preferences/NotificationPreferences.jsx
- **docs: remove Devstack mentions from README instructions**
- **docs: Update edx.rtd.io links to point at new homes**
=> Update README with Tutor instructions; update outdated edx.rtd.io links

src/index.jsx, src/notification-preferences/NotificationCoursesDropdown.jsx, src/notification-preferences/data/thunks.js
Reverts openedx/frontend-app-account#1234
This was a temporary fix to restore the production environment to a stable state. StrictMode was causing duplicate API calls that affected the UI, particularly the courses dropdown.
=> Revert "fix: removed extra api call and strict mode"

.env, .env.development, .env.test, package-lock.json, package.json, src/account-settings/delete-account/ConfirmationModal.jsx, src/account-settings/delete-account/__snapshots__/ConfirmationModal.test.jsx.snap, src/index.scss
>[!WARNING]
> This PR should not be merge to `master` directly, it should point to `master-design-tokens` once the branch has been created. 
This PR updates frontend app account to support CSS variables and the corresponding paragon design tokens.
Changes implemented:
- Replace Paragon SCSS variables with CSS variables.
- Replace deprecated components Input,  ValidationFormGroup
> [!IMPORTANT]
> This PR requires a compatible version with paragon 23 of dependencies because of that the following PRs need to be merged first:
> - [x]  https://github.com/openedx/frontend-platform/pull/689
> - [x] https://github.com/openedx/frontend-plugin-framework/pull/105
> - [x] https://github.com/openedx/frontend-component-header/pull/351
> - [x] …
=> feat: support design tokens and paragon 23 

src/notification-preferences/NotificationCoursesDropdown.jsx
Temporarily disabled notification preferences course dropdown.
To reduce code complexity and respect account level settings for existing users enrolling in new courses, we want to get rid of course level preferences entirely. For this we are disabling dropdown temporarily. In case, users who want to use course level preference will feel some inconvenience, we will get a support request.
Ticket: [INF-1886](https://2u-internal.atlassian.net/browse/INF-1886)
Please describe in detail how you tested your changes.
Include a link to the sandbox for design changes or screenshot for before and after. **Remove this section if it's not applicable.**
|Before|After|
|-------|-----|
|      |      |
=> chore: temporarily disabled notification preferences course dropdown

src/account-settings/certificate-preference/CertificatePreference.jsx, src/account-settings/certificate-preference/test/CertificatePreference.test.jsx, src/account-settings/delete-account/BeforeProceedingBanner.jsx, src/account-settings/delete-account/BeforeProceedingBanner.test.jsx, src/id-verification/IdVerificationPage.jsx, src/id-verification/tests/IdVerificationPage.test.jsx
Replace all usages of the deprecated injectIntl HOC with the useIntl() hook from @edx/frontend-platform/i18n.
Files to refactor:
- src/account-settings/certificate-preference/test/CertificatePreference.test.jsx
- src/account-settings/certificate-preference/CertificatePreference.jsx
- src/account-settings/delete-account/BeforeProceedingBanner.jsx
- src/account-settings/delete-account/BeforeProceedingBanner.test.jsx
- src/id-verification/IdVerificationPage.jsx
- src/id-verification/tests/IdVerificationPage.test.jsx 
Closes #1286
=> Replace of injectIntl with useIntl() 1/10

src/notification-preferences/NotificationSettings.jsx, src/notification-preferences/messages.js
Ticket: [INF-2087](https://2u-internal.atlassian.net/browse/INF-2087)
Since we have removed course level preferences dropdown and default is account level, we need to remove this line:
`Account-level settings apply to all courses.`
Also, modify the second line as follows:
`Daily email notifications are sent at 22:00 UTC. Weekly email notifications are sent every Sunday at 22:00 UTC.`
=> chore: updated the notification section description

src/account-settings/AccountSettingsPage.jsx, src/account-settings/JumpNav.jsx
Our proposal is to modify the width values of jump-nav and content to their state prior to this pull request - https://github.com/openedx/frontend-app-account/pull/784. In this pull request, the width of the jump nav was reduced, and the width of the content was increased. This results in the jump nav appearing very narrow on themes with a maximum container width. Even the phrase "Account Information" does not fit into a single line
After this small fix we'll restore previous state of the columns width, like in Palm
=> feat: Restore jump nav and content width

src/account-settings/EditableField.jsx, src/account-settings/EmailField.jsx, src/id-verification/panels/GetNameIdPanel.jsx, src/id-verification/panels/IdContextPanel.jsx, src/id-verification/tests/panels/GetNameIdPanel.test.jsx, src/id-verification/tests/panels/IdContextPanel.test.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/account-settings/EditableField.jsx
- src/account-settings/EmailField.jsx
- src/id-verification/panels/GetNameIdPanel.jsx
- src/id-verification/tests/panels/GetNameIdPanel.test.jsx
- …
=> Replace of injectIntl with useIntl() 3/10

src/account-settings/DOBForm.jsx, src/account-settings/EditableSelectField.jsx, src/account-settings/JumpNav.jsx, src/account-settings/test/EditableSelectField.test.jsx, src/account-settings/test/JumpNav.test.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/account-settings/EditableSelectField.jsx
- src/account-settings/test/EditableSelectField.test.jsx
- src/account-settings/JumpNav.jsx
- src/account-settings/test/JumpNav.test.jsx
- src/account-settings/DOBForm.jsx
Closes …
=> Replace of injectIntl with useIntl() 7/10

src/id-verification/panels/EnableCameraDirectionsPanel.jsx, src/id-verification/panels/PortraitPhotoContextPanel.jsx, src/id-verification/panels/RequestCameraAccessPanel.jsx, src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx, src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/id-verification/panels/EnableCameraDirectionsPanel.jsx
- src/id-verification/panels/PortraitPhotoContextPanel.jsx
- src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx
- …
=> Replace of injectIntl with useIntl() 8/10

src/account-settings/EmailField.jsx, src/account-settings/_style.scss
Similar PR is opened to the open-release/quince branch:
https://github.com/openedx/frontend-app-account/pull/1025
Fix for the long email field to prevent page break for the mobile view:
If user has a long type email it will be overlap from content of page:
After fix:
=> fix: long email field on account page
