- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/_style.scss
- src/account-settings/actions.js
- src/account-settings/components/EditableField.jsx
- src/account-settings/components/PasswordReset.jsx
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/selectors.js
- src/account-settings/service.js
- src/environment.js
Password reset is broken out into its own component since it has very different behavior from other fields.
> feat: add password reset

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/components/EditableField.jsx
- src/account-settings/components/temp/Input.jsx
- src/account-settings/constants.js
- src/account-settings/reducers.js
- src/account-settings/selectors.js
- src/i18n/injectIntlWithShim.jsx
- Adds Country, Education, Gender, and Spoken Language
- Fixes the injectIntlShim to pass extra arguments to formatMessage
- Adds some functionality to EditableField to help handle unusually formatted data using two new Props `transformValue` and `reverseTransform`
> Account Information: Country, Education, Gender, Spoken Lang

- package-lock.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/components/EditableField.jsx
- src/account-settings/components/EditableField.messages.jsx
- src/account-settings/components/PasswordReset.jsx
- src/account-settings/sagas.js
- src/account-settings/selectors.js
Also fixing a few errors I saw w/r/t prop types.
> Refactoring selectors a bit to organize/take advantage of reselect composition.

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/actions.js
- src/account-settings/components/ThirdPartyAuth.jsx
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/selectors.js
- src/account-settings/service.js
> feat: add linked accounts section

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/components/EditableField.jsx
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/service.js
> feat: add social links

- .travis.yml
> build: validate i18n

- package-lock.json
- package.json
Upgrade frontend-auth to ensure we are dogfooding.
https://github.com/edx/frontend-auth/pull/29
> feat: upgrade frontend-auth

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/actions.js
- src/account-settings/components/ThirdPartyAuth.jsx
- src/account-settings/constants/TIME_ZONES.js
- src/account-settings/constants/index.js
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/service.js
- Adds the time zone field which edits the User Preference (not Account).
- Consolidates fetching of data under the name FETCH_SETTINGS, fetchSettings, etc.
> feat: add time zone

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/actions.js
- src/account-settings/components/BetaLanguageBanner.jsx
- src/account-settings/constants/index.js
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/selectors.js
- src/site-language/actions.js
- src/site-language/constants.js
- src/site-language/index.js
- src/site-language/reducers.js
- src/site-language/sagas.js
- src/site-language/selectors.js
- src/site-language/service.js
https://openedx.atlassian.net/browse/ARCH-716
Note: This may need an additional pass to improve its mobile responsiveness.
> Support for Beta Language Banner

- src/index.jsx
ARCH-785
I'm leaning towards skipping a test (there are currently no tests in this file).  The legacy app didn't have one for this event, and not sure why researchers would ever care about this event anyway. :)
Given that, if someone thinks it is important, just say so.
> ARCH-785: add analytics event edx.user.settings.viewed

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/components/BetaLanguageBanner.jsx
- src/account-settings/selectors.js
This PR follows up on remaining tasks from a review on the previous PR: https://github.com/edx/frontend-app-account/pull/24
> Follow-ups on Beta Language banner

- Makefile
* Update extract_translations to also concat
* Update push_translations to actually push to Transifex
ARCH-748
> fix(i18n): update translation make targets

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/_style.scss
- src/account-settings/components/JumpNav.jsx
> feat: add jump nav

- src/account-settings/service.js
Might be convenient to add a postUrlEncoded() method in frontend-auth.
> fix(delete my account): url encode

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/components/EditableField.jsx
- src/account-settings/components/EmailField.jsx
- src/account-settings/components/PasswordReset.jsx
- src/account-settings/components/ThirdPartyAuth.jsx
- Adding more spacing between sections.
- Adding pencil icon to “Edit” buttons.
- adding aria-level=“3” to h6 elements
> Addressing various UX/a11y feedback

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/_style.scss
Includes an update to nav labels in the site header
> fix: increase clarity of a11y landmarks

- package-lock.json
- package.json
- src/index.jsx
This should, I think, solve our IE/Edge problems.  They don't support many of FormData's methods, which is a useful utility class for dealing with form... data.
https://developer.mozilla.org/en-US/docs/Web/API/FormData
> Adding formdata polyfill for IE and Edge.

- README.rst
- package-lock.json
- package.json
- webpack/webpack.prod.config.js
LTR and RTL css files are 50kb each down from 295kb each.
> feat: add purgecss to remove unused css from production build

- package-lock.json
- package.json
- src/account-settings/JumpNav.jsx
Leverages the react-scrollspy package.
> feat: add scrollspy to jump nav

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/actions.js
- src/account-settings/reducers.js
- src/account-settings/sagas.js
- src/account-settings/selectors.js
- src/account-settings/service.js
- src/account-settings/third-party-auth/ThirdPartyAuth.jsx
- src/account-settings/third-party-auth/data/actions.js
- src/account-settings/third-party-auth/data/reducers.js
- src/account-settings/third-party-auth/data/sagas.js
- src/account-settings/third-party-auth/data/service.js
- src/account-settings/third-party-auth/index.js
NOTE: At present, I couldn't figure out how to test this in devstack.  That sucks.
> Modularizing third party auth.

- src/account-settings/delete-account/ConfirmationModal.jsx
- src/account-settings/delete-account/ConfirmationModal.test.jsx
- src/account-settings/delete-account/DeleteAccount.jsx
- src/account-settings/delete-account/DeleteAccount.test.jsx
- src/account-settings/delete-account/SuccessModal.jsx
- src/account-settings/delete-account/SuccessModal.test.jsx
- src/account-settings/delete-account/__snapshots__/ConfirmationModal.test.jsx.snap
- src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap
- src/account-settings/delete-account/__snapshots__/SuccessModal.test.jsx.snap
- src/account-settings/delete-account/data/reducers.js
- src/account-settings/delete-account/data/reducers.test.js
- comprehensive reducer tests
- UI snapshot tests for most (all?) states
> Adding tests for delete account.

- .travis.yml
- package-lock.json
- package.json
- cleaning up .travis.yml
- bumping node-sass
> node 12 and cleanup

- src/components/App.jsx
> fix: remove youtube logo from footer

- README.rst
@davidjoy: I don't know if you want this in other repos as well?
> clean up readme

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/BetaLanguageBanner.jsx
- src/account-settings/JumpNav.jsx
- src/account-settings/data/sagas.js
- src/account-settings/data/selectors.js
- src/data/reducers.js
- src/index.jsx
- Ceased using i18nReducer and setLocale from frontend-i18n.
- Caused a number of dropdown menus to re-localize properly.
- Published LOCALE_CHANGED event when changing locale so that AppProvider updates the AppContext accordingly.
> fix: all account settings page elements now re-localize when the locale changes

- src/account-settings/coaching/data/service.js
Was missing extraction of data key in call
> Fix coaching data API call

- src/account-settings/delete-account/ConfirmationModal.jsx
- src/account-settings/delete-account/data/sagas.js
- src/account-settings/delete-account/messages.js
Added error message in case of invalid password
**Sandbox**
N/A
If you've been tagged for review, please check your corresponding box once you've given the :+1:.
> Added invalid password check on delete

- src/id-verification/CameraHelp.jsx
- src/id-verification/_id-verification.scss
- src/id-verification/data/service.js
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SummaryPanel.jsx
@edx/masters-devs-cosmonauts This PR is ready for review
See [MST-243](https://openedx.atlassian.net/browse/MST-243)
Completed:
- Fix padding issues on "next" button
- Expand/collapse help text on photo panels to avoid overwhelming the user
- Made name change and submit button functional
> IDV UI improvements

- src/account-settings/JumpNav.jsx
Turn of the side navigation when demographics is not turned on.
> Hide demographics sidenav link when demographics is off

- src/account-settings/coaching/CoachingConsent.messages.js
> [MICROBA-368] Updated text for the Coaching consent to align with

- src/account-settings/data/selectors.js
- src/account-settings/demographics/Checkboxes.jsx
- src/account-settings/demographics/DemographicsSection.jsx
- src/account-settings/demographics/data/service.js
- src/account-settings/demographics/test/DemographicsSection.test.jsx
- src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
[MICROBA-309]
- Fix defect in ethnicityFieldDisplay function. Check to make sure the prop exists before trying to access.
- Add error handling for the scenario that the Demographics service isn't available/isn't responding to API calls. Show alert on PATCH calls to inform user that service is temporarily unavailable
- Add tests for DemographicsSection component
> MICROBA-309 | Error handling, tests, misc. updates for Demographics

- src/account-settings/demographics/DemographicsSection.jsx
[MICROBA-465]
- Fix Demographics alert behavior on Accounts page to only display on Demographics errors
> MICROBA-465 | Fix Demographics alert behavior

- src/id-verification/panels/SubmittedPanel.jsx
@edx/masters-devs-cosmonauts This PR is ready for review.
Added survey to the end of the IDV experience for user testing. The survey content may change based on feedback, but it can still be edited after this PR is merged.
> Add SurveyMonkey widget to IDV submitted page

- src/account-settings/data/constants.js
- src/account-settings/demographics/DemographicsSection.messages.jsx
[MICROBA-471]
Add support for self-employed option added to the work status options on the UserDemographics model.
> MICROBA-471 | Add 'self-employed' option to work status options

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/JumpNav.jsx
- src/account-settings/data/service.js
- src/account-settings/demographics/test/DemographicsSection.test.jsx
- src/account-settings/test/JumpNav.test.jsx
- src/account-settings/test/__snapshots__/JumpNav.test.jsx.snap
[MICROBA-474]
- Add logic to show (or hide) the "Optional Information" (Demographics questions) section on the Account settings page via call to new LMS API
- Remove unused import from DemographicsSection.test.jsx
> MICROBA-474 | Gate Demographics questions and link via LMS API call

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/demographics/DemographicsSection.jsx
- src/account-settings/demographics/DemographicsSection.messages.jsx
Added in a check for a locationHash and loaded state to
scroll to the section in the URL so that the page would load to a Nav
Section after loading data.
> [MICROBA-484] Scroll to section based on URL

- src/id-verification/panels/GetNameIdPanel.jsx
- src/id-verification/panels/RequestCameraAccessPanel.jsx
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SubmittedPanel.jsx
Fix to properly send events to Segment.
> Changed sendTrackingLogEvent to sendTrackEvent

- src/account-settings/demographics/data/service.js
[MICROBA-488]
- Improve error handling in DemographicsSection
Screenshot of field level error when Demographics is up but the input is too long for the `gender_description` field:
And again for `work_status_description`:
Alert is displayed when Demographics service cannot be contacted:
> MICROBA-488 | Improve error handling in DemographicsSection

- package-lock.json
- package.json
- src/id-verification/panels/SummaryPanel.jsx
[MST-339: Add spinner to IDV submission](https://openedx.atlassian.net/browse/MST-339)
Spinner added and button disabled while uploading images to avoid duplicate submissions. Paragon dependency is updated from 7.1.5 => 9.1.0 with this PR.
---
> Update Paragon and add loading state + spinner to IDV summary page

- src/id-verification/panels/SubmittedPanel.jsx
[MST-343: Remove survey from new IDV workflow](https://openedx.atlassian.net/browse/MST-343)
@edx/masters-devs-cosmonauts
> Remove SurveyMonkey widget from IDV

- package-lock.json
- package.json
- src/id-verification/panels/GetNameIdPanel.jsx
- src/id-verification/panels/IdContextPanel.jsx
- src/id-verification/panels/PortraitPhotoContextPanel.jsx
- src/id-verification/panels/RequestCameraAccessPanel.jsx
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SubmittedPanel.jsx
- src/id-verification/panels/SummaryPanel.jsx
- src/id-verification/panels/TakeIdPhotoPanel.jsx
- src/id-verification/panels/TakePortraitPhotoPanel.jsx
- src/id-verification/tests/Camera.test.jsx
- src/id-verification/tests/ExistingRequest.test.jsx
- src/id-verification/tests/IdVerificationContext.test.jsx
- src/id-verification/tests/panels/GetNameIdPanel.test.jsx
- src/id-verification/tests/panels/IdContextPanel.test.jsx
- src/id-verification/tests/panels/PortraitPhotoContextPanel.test.jsx
- src/id-verification/tests/panels/RequestCameraAccessPanel.test.jsx
- src/id-verification/tests/panels/ReviewRequirementsPanel.test.jsx
- src/id-verification/tests/panels/SubmittedPanel.test.jsx
- src/id-verification/tests/panels/SummaryPanel.test.jsx
- src/id-verification/tests/panels/TakeIdPhotoPanel.test.jsx
- src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx
[MST-276](https://openedx.atlassian.net/browse/MST-276)
> Add React Testing Library and write unit tests for IDV

- src/account-settings/data/constants.js
- src/account-settings/demographics/DemographicsSection.messages.jsx
[MICROBA-405]
- Add missing demographics income option
> MICROBA-405 | Add missing demographics income option

- src/id-verification/Camera.jsx
- src/id-verification/_id-verification.scss
Updated camera and canvas ratio to match, and updated ranges for landmarks. Ensures that canvas and video size are the same so that tracking boxes are placed in the correct position on the canvas.
Tested on Chrome, Safari, and Firefox.
> Fix for blazeface/camera issue

- src/account-settings/reset-password/RequestInProgressAlert.jsx
- src/data/reducers.js
- src/index.jsx
- src/logistration/ConfirmationAlert.jsx
- src/logistration/ConfirmationAlert.test.jsx
- src/logistration/LoginPage.jsx
- src/logistration/__snapshots__/ConfirmationAlert.test.jsx.snap
- src/logistration/data/reducers.js
- src/logistration/data/sagas.js
- src/logistration/data/selectors.js
- src/logistration/data/service.js
- src/logistration/data/utils/reduxUtils.js
- src/logistration/data/utils/reduxUtils.test.js
- src/logistration/forgot-password/ForgotPasswordPage.jsx
- src/logistration/forgot-password/data/actions.js
- src/logistration/forgot-password/data/reducers.js
- src/logistration/forgot-password/data/sagas.js
- src/logistration/forgot-password/data/selectors.js
- src/logistration/forgot-password/data/service.js
- src/logistration/forgot-password/index.js
- src/logistration/forgot-password/messages.js
- src/logistration/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/logistration/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/logistration/index.js
> Add forgot password page.

- src/id-verification/panels/SubmittedPanel.jsx
Re-added a survey to the submitted page. This survey has the same questions as they first survey added (from an [earlier PR](https://github.com/edx/frontend-app-account/pull/253)).
> Added SurveyMonkey Survey to IDV submitted page

- src/logistration/LoginPage.jsx
- src/logistration/_style.scss
- src/logistration/tests/LoginPage.test.jsx
- src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
- Added transition to collapsible menu
- Moved `forget password` and `other sign in issues` under menu
[VAN-62](https://openedx.atlassian.net/browse/VAN-62)
> Add login help collapsible menu

- src/index.jsx
- src/logistration/LoginPage.jsx
- src/logistration/RegistrationPage.jsx
- src/logistration/_style.scss
- src/logistration/data/constants.js
- src/logistration/index.js
- src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
> Logistration code refactoring.

- src/id-verification/panels/SubmittedPanel.jsx
IDV has been increased to 100%, so survey can be removed from the end of the new flow.
> Removed SurveyMonkey survey

- src/id-verification/Camera.jsx
- src/id-verification/IdVerification.messages.js
Realtime feedback for screen readers has been added to the face detection feature to make IDV more accessible for visually impaired users. 
Position related feedback will only be given to users if exactly one face is detected. If one face is detected a user will be told if they are in a good or bad position. If they are in a bad position, they will also be told what area they are in (i.e. "Incorrect position. Bottom left."). 
Link to video example: https://imgur.com/a/UrsjXFn
> Add realtime feedback for screenreaders during face detection

- src/logistration/LoginPage.jsx
- src/logistration/data/actions.js
- src/logistration/data/reducers.js
- src/logistration/data/sagas.js
- src/logistration/data/selectors.js
- src/logistration/data/service.js
- src/logistration/tests/LoginPage.test.jsx
Redirect the learner after the login based on the argument in the url. 
Url can have two param's next and course id.
- If there's no param in url then learner would be redirected to dashboard.
- In case of course id it would be redirected to that course.
- In case of next learner would be redirected to the mentioned url in next. 
[VAN-4](https://openedx.atlassian.net/browse/VAN-4)
> redirect after login

- src/account-settings/reset-password/RequestInProgressAlert.jsx
- src/logistration/LoginHelpLinks.jsx
- src/logistration/LoginHelpLinks.messages.jsx
- src/logistration/LoginPage.jsx
- src/logistration/RegistrationPage.jsx
- src/logistration/_style.scss
- src/logistration/forgot-password/ForgotPasswordPage.jsx
- src/logistration/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/logistration/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/logistration/tests/LoginPage.test.jsx
- src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
Moved login page need help links into its own component and used that on both login and forgot password pages.
VAN-17
> Add need help links on forgot password page.

- src/account-settings/EditableField.jsx
- src/account-settings/EmailField.jsx
- src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
- src/id-verification/Camera.jsx
- src/id-verification/ImagePreview.jsx
> suppressed pii for hot jar

- src/id-verification/Camera.jsx
- src/id-verification/tests/Camera.test.jsx
Added tracking events for when users enable and disable face detection for both the ID and portrait photo pages.
> Add tracking events for face detection

- src/id-verification/panels/GetNameIdPanel.jsx
> Fix onSubmit for IDV name change form

- package-lock.json
- package.json
- public/index.html
Update frontend-build in order to allow the capability to change the webpack.output.publicPath from environment variables.
> fix: Update frontend-build and frontend-platform

- src/id-verification/IdVerificationPage.jsx
The course_id was being parsed incorrectly in the IDV flow, preventing users from submitting their photos. Related to https://github.com/edx/edx-platform/pull/25792
> Parse course_id query string correctly

- src/id-verification/IdVerification.messages.js
- src/id-verification/data/service.js
- src/id-verification/panels/SummaryPanel.jsx
- src/id-verification/tests/panels/SummaryPanel.test.jsx
[MST-502](https://openedx.atlassian.net/browse/MST-502)
Added specific error messages for possible 400 errors on photo submission.
> [MST-502] Add more descriptive errors for IDV submission

- src/id-verification/IdVerification.messages.js
[MST-604](https://openedx.atlassian.net/browse/MST-604)
Small copy update to lessen learner confusion.
> [MST-604] Change 'Retake Photo' to 'Retake Photo?'

- package-lock.json
- package.json
Trying to resolve peer dependency issues with paragon 13.
> Bumping frontend-platform to 1.8.4

- package-lock.json
- package.json
This new version removes an unnecessary peer dependency on paragon.  Hoping this fixes our build issues.
> Bumping footer version to 10.1.4

- src/account-settings/AccountSettingsPage.jsx
Workaround an issue caused by a known interplay between React and Google Translate that we have no control over. 
[TNL-7867](https://openedx.atlassian.net/browse/TNL-7867)
React issue: https://github.com/facebook/react/issues/11538
> Workaround an issue between React and Google Translate

- renovate.json
Auto merge `["minor", "patch", "pin", "digest"]`. This will create the PR immediately and wait 3 `stabilityDays` before automerging.
> Update renovate.json to automerge minor releases of Paragon

- src/account-settings/AccountSettingsPage.jsx
The underlying issue has been resolved in edx/paragon#657
Reverts edx/frontend-app-account#397
> Revert "Workaround an issue between React and Google Translate"

- public/index.html
- src/id-verification/IdVerificationContextProvider.jsx
- src/id-verification/data/service.js
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SummaryPanel.jsx
- src/id-verification/tests/panels/ReviewRequirementsPanel.test.jsx
- src/id-verification/tests/panels/SummaryPanel.test.jsx
[MST-655](https://openedx.atlassian.net/browse/MST-655)
Related backend PR: https://github.com/edx/edx-platform/pull/26925
> [MST-655] Add Optimizely to be used with IDV experiments

- src/id-verification/IdVerification.messages.js
- src/id-verification/IdVerificationContextProvider.jsx
- src/id-verification/panels/GetNameIdPanel.jsx
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SummaryPanel.jsx
- src/id-verification/tests/IdVerificationContextProvider.test.jsx
- src/id-verification/tests/panels/GetNameIdPanel.test.jsx
- src/id-verification/tests/panels/ReviewRequirementsPanel.test.jsx
- src/id-verification/tests/panels/SummaryPanel.test.jsx
Reverts edx/frontend-app-account#414
Works on stage, but breaking in prod. Reverting until the cause is identified.
> Revert "[MST-535] Prevent IDV name change if name is managed by a third party"

- src/id-verification/IdVerification.messages.js
- src/id-verification/IdVerificationContextProvider.jsx
- src/id-verification/panels/GetNameIdPanel.jsx
- src/id-verification/panels/ReviewRequirementsPanel.jsx
- src/id-verification/panels/SummaryPanel.jsx
- src/id-verification/tests/IdVerificationContextProvider.test.jsx
- src/id-verification/tests/panels/GetNameIdPanel.test.jsx
- src/id-verification/tests/panels/ReviewRequirementsPanel.test.jsx
- src/id-verification/tests/panels/SummaryPanel.test.jsx
[MST-535](https://openedx.atlassian.net/browse/MST-535)
Rework of https://github.com/edx/frontend-app-account/pull/414, fixed so that `getProfileDataManager` is returns a value rather than a promise.
> [MST-535] Prevent IDV name change if name is managed by a third party

- renovate.json
> build(renovate): automerge devDependencies

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/EditableField.jsx
- src/account-settings/OneTimeDismissibleAlert.jsx
- src/account-settings/data/sagas.js
- src/account-settings/data/service.js
> [MST-800] Add Verified Name field and success alert to the Account Settings page

- src/account-settings/AccountSettingsPage.jsx
If a learner requests a profile name change or verified name change that requires ID verification, their ID verification submission may be rejected. This code change changes the verified name that is displayed in this case. If a learner's most recent verified name record has been denied, and the learner has a previously approved verified name, display that. If If a learner's most recent verified name record has been denied, and the learner either has no previously verified name records or no previous verified name records at all, do not show a verified name field.
It also refactors the code to better support UI treatments for other verified name statuses, like pending and submitted.
MST-954 (https://openedx.atlassian.net/browse/MST-954)
> feat: Change Which VerifiedName Record is Displayed When Most Recent VerifiedName is Denied

- src/account-settings/AccountSettingsPage.jsx
[MST-1057](https://openedx.atlassian.net/browse/MST-1057)
---
> [MST-1057] Display pending name when in "submitted" state

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/AccountSettingsPage.messages.jsx
[MST-1091](https://openedx.atlassian.net/browse/MST-1091)
> [MST-1091] Update IDV failure message to be more generic

- package-lock.json
- package.json
Ran:
npm install @edx/frontend-component-header@latest
npm install @edx/frontend-build@latest
> chore: upgrade frontend-build and frontend-component-header

- src/account-settings/AccountSettingsPage.messages.jsx
- src/account-settings/name-change/messages.js
- src/account-settings/name-change/test/NameChange.test.jsx
- src/id-verification/IdVerification.messages.js
https://openedx.atlassian.net/browse/MST-1269
> [MST-1269] Change language referring to government ID

- src/id-verification/IdVerification.messages.js
https://openedx.atlassian.net/browse/MST-1372
> [MST-1372] Remove dashboard reference from IDV submission confirmation

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/JumpNav.jsx
- src/account-settings/_style.scss
- src/account-settings/delete-account/DeleteAccount.jsx
- src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap
- src/account-settings/demographics/DemographicsSection.jsx
- src/account-settings/demographics/test/__snapshots__/DemographicsSection.test.jsx.snap
- src/account-settings/test/__snapshots__/JumpNav.test.jsx.snap
- src/id-verification/_id-verification.scss
- src/id-verification/panels/IdContextPanel.jsx
- src/id-verification/panels/PortraitPhotoContextPanel.jsx
- src/id-verification/panels/ReviewRequirementsPanel.jsx
Remove usage of SCSS variables so that the MFE doesn't need SCSS variables at build-time.
Screenshots before and after this PR:
| Before | After |
|---|---|
|![Screenshot_20220509_140129](https://user-images.githubusercontent.com/118837/167373765-3b28e8ac-4a73-40c2-ad0d-6384768816d7.png)|![Screenshot_20220509_140030](https://user-images.githubusercontent.com/118837/167373753-85f60978-63dd-49b5-9d81-3ec9523ce741.png)|
|![Screenshot_20220509_140253](https://user-images.githubusercontent.com/118837/167374027-828b8d0f-b15c-46f2-bd05-acfca34c9a6e.png)|![Screenshot_20220509_140309](https://user-images.githubusercontent.com/118837/167373965-577a5070-805d-4757-9c8f-ab680d07266d.png)|
|![Screenshot_20220509_140433](https://user-images.githubusercontent.com/118837/167374198-1d5c3825-4615-4413-b90a-c …
> feat: remove usage of scss variables

- src/account-settings/EditableField.jsx
- src/account-settings/delete-account/DeleteAccount.test.jsx
- src/id-verification/tests/IdVerificationPage.test.jsx
- src/id-verification/tests/VerifiedNameContextProvider.test.jsx
- src/id-verification/tests/panels/TakePortraitPhotoPanel.test.jsx
**Description:** 
Removing fragments to satisfy `react/jsx-no-useless-fragment` resulted in TypeError, reverted those changes & ignored the rule.
> Reverted changes made to satisfy jsx-no-useless-fragment rule

- src/account-settings/AccountSettingsPage.messages.jsx
Update language based on legal's requirements.
> fix: update dob form language

- .github/workflows/update-browserlist.yml
[Automate browserslist DB update ](https://github.com/openedx/frontend-wg/issues/101)
Added a Github workflow that would run periodically(every 5 minutes for now but weekly for production) and update browserslist DB automatically.
Used [pull_request_creator](https://github.com/edx/testeng-ci/blob/master/jenkins/pull_request_creator.py) action by Arbi-BOM which creates PRs automatically.
> Automate Browserlist DB Update

- src/account-settings/AccountSettingsPage.messages.jsx
Legal wanted slightly different wording so they get slightly different wording.
> chore: trivial changes to compliance form text

- README.rst
@davidjoy think it's time to remove this?
> docs: Remove old maintaining team from README

- package-lock.json
- package.json
Updated frontend-platform version with GA4 implementation.
[FC-0014 - Google Analytics 4 Upgrade](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3668312128/FC-0014+-+Google+Analytics+4+Upgrade)
> [FC-0014] update frontend-platform version to v4.2.0

- package-lock.json
- package.json
- src/notification-preferences/NotificationCourses.jsx
- src/notification-preferences/NotificationPreferenceApp.jsx
- src/notification-preferences/NotificationPreferenceRow.jsx
- src/notification-preferences/NotificationPreferences.jsx
- src/notification-preferences/ToggleSwitch.jsx
- src/notification-preferences/data/actions.js
- src/notification-preferences/data/reducers.js
- src/notification-preferences/data/selectors.js
- src/notification-preferences/data/service.js
- src/notification-preferences/data/thunks.js
- src/notification-preferences/messages.js
Integrated Notification Preferences API
Ticket: [INF-892](https://2u-internal.atlassian.net/browse/INF-892)
> feat: integrate notification preferences api

- src/index.jsx
- src/notification-preferences/NotificationCourses.jsx
- src/notification-preferences/NotificationCourses.test.jsx
- src/notification-preferences/NotificationPreferences.jsx
- src/notification-preferences/data/reducers.js
- src/notification-preferences/data/reducers.test.js
- src/notification-preferences/data/selectors.js
- src/notification-preferences/data/service.js
- src/notification-preferences/data/thunks.js
- src/notification-preferences/messages.js
- Implement Course list pagination using the load more button.
- Added load more courses button to load the next courses.
- Update redux structure for course list to handle pagination
- Added test cases
> feat: load more courses button in notification courses list

- package-lock.json
- src/i18n/index.js
Import `paragonMessage` in `src/i18n/index.js`
Reference issue:
https://github.com/openedx/frontend-app-gradebook/issues/340
> chore: add paragon messages

- src/index.scss
- src/notification-preferences/NotificationPreferenceApp.jsx
- src/notification-preferences/NotificationPreferences.jsx
**[INF-984](https://2u-internal.atlassian.net/browse/INF-984)**
- update feedback widget location.
> style: change feedback widget location

- src/notification-preferences/NotificationPreferenceRow.jsx
- src/notification-preferences/messages.js
Changed overlay position of notification info to right
Removed notification preference text that were not being used and added some new text
Ticket Link: [INF-1011](https://2u-internal.atlassian.net/browse/INF-1011)
> fix: changed overlay position and updated notification info text

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/data/utils/sagaUtils.js
- src/account-settings/hoc.jsx
- src/account-settings/hoc.test.jsx
- src/account-settings/site-language/actions.js
- src/account-settings/site-language/sagas.js
- src/id-verification/tests/panels/SummaryPanel.test.jsx
- src/notification-preferences/NotificationPreferences.test.jsx
This PR removes `history` package from this MFE.
> refactor: remove history pacakge

- package.json
Reverts openedx/frontend-app-account#859
> Revert "fix(deps): update dependency @tensorflow-models/blazeface to v0.1.0"

- package.json
Reverts openedx/frontend-app-account#867
> Revert "fix(deps): update dependency @edx/frontend-platform to v5.3.0"

- src/notification-preferences/NotificationCourses.jsx
[INF-1061](https://2u-internal.atlassian.net/browse/INF-1061)
Removed underline on hover, just show cursor change (pointing hand)
**Screenshot**
> fix: removed underline from course name

- Makefile
- package-lock.json
- package.json
Similar to https://github.com/openedx/frontend-app-communications/pull/187.
- install atlas
- remove `--filter` to pull all languages by default
- use ATLAS_OPTIONS to allow custom `--filter`
- include frontend-platform in `atlas pull`
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
> feat: tutor-mfe compatiblilty for atlas pull | FC-0012

- src/notification-preferences/messages.js
Added title for new notification for reported content.
https://2u-internal.atlassian.net/browse/INF-1242
> feat: added notification title for contentReported

- src/notification-preferences/NotificationPreferenceApp.jsx
- src/notification-preferences/NotificationPreferenceRow.jsx
- src/notification-preferences/NotificationPreferences.test.jsx
- src/notification-preferences/ToggleSwitch.jsx
[INF-1243](https://2u-internal.atlassian.net/browse/INF-1243)
Added following test cases for notification preference UI.
1. It updates all preferences in the column on web channel click when toggle state is true
2. It updates all preferences in the column on web channel click when toggle state is false
> test: added test cases to change toggle based on channel

- src/notification-preferences/messages.js
Fixed text appearance cause due to [PR](https://github.com/openedx/frontend-app-account/pull/990/files)
> fix: fixed text appearance

- package-lock.json
> chore: regenerated package lock file

- src/notification-preferences/NotificationPreferenceRow.jsx
- src/notification-preferences/messages.js
Removed core preference option from ORA notification app.
> fix: removed core type from ora app

- src/notification-preferences/NotificationPreferenceRow.jsx
- src/notification-preferences/messages.js
Updated notification app name from ora -> grading
> fix: updated notification app name to grading

- package-lock.json
- package.json
- src/index.jsx
partially reverts #1044 since its breaking with footer-edx
> fix: reverted footer plugin to use simple footer

- src/notification-preferences/EmailCadences.jsx
- src/notification-preferences/NotificationPreferenceApp.jsx
- src/notification-preferences/NotificationPreferenceColumn.jsx
- src/notification-preferences/NotificationTypes.jsx
- src/notification-preferences/data/constants.js
- src/notification-preferences/data/thunks.js
- src/notification-preferences/data/utils.js
[INF-1360](https://2u-internal.atlassian.net/browse/INF-1360)
Fixed environment variable issue for email cadence.
> fix: fixed environment variable issue for email cadence

- src/notification-preferences/NotificationPreferenceApp.jsx
- src/notification-preferences/NotificationPreferences.jsx
[INF-1415](https://2u-internal.atlassian.net/browse/INF-1415)
Web and Email heading is showing during loading indicator. Remove bottom margin from web and email heading.
**Solution**  
Web and Email heading is not showing during loading indicator.
Removed Bottom margin from web and email heading
> fix: fix loading and margin issues

- src/notification-preferences/NotificationPreferenceColumn.jsx
- src/notification-preferences/data/selectors.js
- src/notification-preferences/data/service.js
- src/notification-preferences/data/thunks.js
Removed all code for the channel-wide toggle feature on the notification preferences page, as the feature is no longer required.
> refactor: removed the channel wide toggle feature

- .github/pull_request_template.md
- README.rst
- catalog-info.yaml
[INF-1482](https://2u-internal.atlassian.net/browse/INF-1482)
1. updated Readme file according to mentioned specifications in https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055/decisions/0003-readme-specification.html
2. added a catalog-info file https://docs.openedx.org/en/latest/developers/how-tos/add-a-catalog-file.html
> docs: updated read me and catalog info files

- README.rst
Quick PR for https://2u-internal.atlassian.net/browse/COSMO-419 as part of setting up https://github.com/edx/frontend-plugin-persona/pull/1
> docs: add local module dev info

- src/notification-preferences/messages.js
Ticket: [INF-1580](https://2u-internal.atlassian.net/browse/INF-1580)
added the `notificationTitle` for `oraGradeAssigned`
> chore: added notificationTitle for oraGradeAssigned

- package-lock.json
- package.json
- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/EditableSelectField.jsx
- src/account-settings/data/reducers.js
- src/account-settings/data/selectors.js
- src/notification-preferences/messages.js
Rebase 2u-main brach with master
> refactor: sync 2u-main with master

- src/notification-preferences/messages.js
Ticket: [INF-1653](https://2u-internal.atlassian.net/browse/INF-1653)
updated the `notification title` for `oraGradeAssigned` to "Essay assignment grade received"
> chore: updated notificationTitle for oraGradeAssigned

- package-lock.json
- package.json
- src/notification-preferences/messages.js
Rebase 2u-main branch with latest master branch
> chore: rebase 2u-main with master 

- package-lock.json
- package.json
- src/account-settings/delete-account/__snapshots__/ConfirmationModal.test.jsx.snap
Merge the latest changes from master to 2u-main.
> Merge latest changes to 2u-main

- .github/workflows/ci.yml
- package-lock.json
- package.json
- Rebase 2u-main branch with master branch
> chore: rebase with master

- .env
- .env.development
- .env.test
- package-lock.json
- src/account-settings/delete-account/DeleteAccount.jsx
- src/account-settings/delete-account/PrintingInstructions.jsx
- src/account-settings/delete-account/__snapshots__/DeleteAccount.test.jsx.snap
Rebase 2u-main branch with master branch
> chore: rebase with master 

- src/notification-preferences/NotificationPreferences.jsx
[INF-1655](https://2u-internal.atlassian.net/browse/INF-1655)
Fixed the broken link to notifications documentation on the preferences page.
> fix: fixed url break issue

- src/notification-preferences/NotificationPreferences.jsx
Description
Rebased 2u-main with master
> Rebased 2u-main with master

- package-lock.json
- package.json
> fix: rebase with 2u

- catalog-info.yaml
- openedx.yaml
Description:
Update catalog-info.yaml file for release data, as the BTR script has been updated https://github.com/openedx/repo-tools/issues/439 to read the catalog-info.yaml file if it has release data, we are updating the catalog-info file as per https://github.com/openedx/axim-engineering/issues/882
> Update catalog-info-file for release data.

- catalog-info.yaml
- openedx.yaml
- package-lock.json
- package.json
update 2u-main branch with master
> chore: sync with master

- src/notification-preferences/messages.js
Updated oraStaffNotification to oraStaffNotifications in title text for notification preference page , As we have updated the key on backend
https://2u-internal.atlassian.net/browse/INF-1838
> fix: Update course preference title for ora submission

- src/index.jsx
- src/notification-preferences/NotificationCoursesDropdown.jsx
- src/notification-preferences/data/thunks.js
Removed extra api call i.e., fetchCourseList  and strict mode.
> fix: removed extra api call and strict mode

- package-lock.json
- package.json
- src/index.jsx
- src/plugin-slots/FooterSlot/README.md
- src/plugin-slots/README.md
https://app.pr-1230-50bd49.sandboxes.opencraft.hosting/account/
> feat: import `FooterSlot` from component package instead of slot package

- package-lock.json
- src/notification-preferences/NotificationCoursesDropdown.jsx
> Sync master to design tokens

- src/account-settings/AccountSettingsPage.jsx
- src/account-settings/test/AccountSettingsPage.test.jsx
- src/id-verification/Camera.jsx
- src/id-verification/tests/Camera.test.jsx
Reverts openedx/frontend-app-account#1314
Hi @diana-villalvazo-wgu, I’m reverting this PR as it is causing issues in the stage environment. I’ve attached the error details for your reference.
> Revert "Replace of injectIntl with useIntl() 10/10"
